# Generated by Django 3.2.6 on 2021-08-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='payment',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
