# Generated by Django 3.2.6 on 2021-08-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20210829_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(default='Cash on Delivery', max_length=200),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
