# Generated by Django 3.2.6 on 2021-08-30 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0014_remove_order_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='refund_requested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(null=True, upload_to='returns')),
                ('reason', models.CharField(choices=[('Size', 'Size is not appropriate'), ('Not Needed', 'Product not needed now'), ('Damaged', 'Product is damaged'), ("Don't match", 'Product dont match the description'), ('Color', 'Color is not same as i wanted/shown')], max_length=150)),
                ('UPI_NUMBER', models.CharField(max_length=25)),
                ('accepted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
