# Generated by Django 3.2.6 on 2021-08-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_refund_requested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund_requested',
            old_name='UPI_NUMBER',
            new_name='Account_Number',
        ),
    ]
