# Generated by Django 3.2.6 on 2021-08-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_rename_upi_number_refund_requested_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_request',
            field=models.BooleanField(default=False),
        ),
    ]
